title: "Metadata Evaluation Criteria"
description: "A documentation site for metadata evaluation standards"
baseurl: "/metadata-evaluation-criteria"
url: "https://bmir-radx.github.io"
#remote_theme: just-the-docs/just-the-docs
remote_theme: just-the-docs/just-the-docs

# Enable navigation
has_toc: true
permalink: pretty

# GitHub Pages settings
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude unnecessary files
exclude:
  - README.md
  - node_modules/
